# -*- coding: utf-8 -*-
"""
Created on Mon Feb 10 12:05:52 2025

@author: brainardlab
"""

import importlib.metadata
import dill as pickled
import sys
import os
import numpy as np
import jax
jax.config.update("jax_enable_x64", True)
# Machine-specific repository paths are stored in config/hardcoded_paths_*.json.
from analysis.utils_load import get_path
from analysis.color_thres import color_thresholds
from analysis.config_generator import ConfigGenerator
from analysis.utils_communication import CommunicateViaTextFile,\
    ExperimentFileManager, get_experiment_info_custom, get_comment_after_session
from analysis.trial_sequence import ExperimentTrialSequence, shuffle_sobol_trials
from analysis.gen_expt_trials import ExptTrialGeneration, LoadExptInfo

# load AEPsych
from aepsych.server import AEPsychServer
from aepsych_client import AEPsychClient
# Get the installed version of AEPsych
python_version  = sys.version
aepsych_version = importlib.metadata.version("aepsych")

# --------------------------------------------------------------
# Overview:
# --------------------------------------------------------------
# This script is a modified version of run_4d_expt.py, designed to provide 
# subjects with practice trials before beginning the actual experimental trials 
# in each session. The key differences from the main experiment script are:
#
# (1) **Separate Practice File Storage:**
#     - Output files generated by this script are stored in a dedicated `/practice` 
#       folder to clearly distinguish them from actual experimental data.
#
# (2) **Trial Selection:**
#     - Only Sobol-generated trials are used, interleaved with MOCS trials.
#
# (3) **Unique MOCS Trials:**
#     - The pregenerated MOCS trials used in practice are different from those
#       used in the actual experiment to prevent overtraining.
#
# (4) **Faster Trial Execution:**
#     - `max_wait_time_bumpingMOCS` is significantly shorter, as Sobol trials 
#       are generated quickly and do not require long computational delays.
#
# (5) **No Trial Placement Visualization:**
#     - Unlike the actual experiment, this script does not include visualization 
#       for trial placement, keeping the focus on practice execution.
# --------------------------------------------------------------

#% Define basic information about the experiment
# ---------------------------------------------
# This experiment operates in a 4D space:
# - We vary two components of the reference stimulus and two delta values to derive the comparison stimulus.
# - Stimuli are presented in the isoluminant plane within the display's gamut.
#
# Transformation between color spaces:
# - The experiment operates in Wishart space (bounded within [-1,1]).
# - A transformation matrix converts Wishart space stimuli to DKL space 
#   (where axes are L-M and S) and to RGB space for Unity display.
#
# Unique setup with two computers:
# - Computer A determines trial interleaving (MOCS and AEPsych) and sends RGB values
#   to Computer B via a text file on a shared network disk.
# - Computer B reads the text file and displays the stimulus without handling trial logic.

COLOR_DIMENSION = 4  # Defines the dimensionality of the thresholding experiment
plane_2D = 'Isoluminant plane'  # Stimuli are constrained to the isoluminant plane

# Define base directory for experiment files
baseDir = get_path("dropbox_root_windows")

# Load transformation matrices to map between Wishart, DKL, and RGB spaces
color_thres_data = color_thresholds(COLOR_DIMENSION // 2, 
                                    baseDir, 
                                    plane_2D=plane_2D)
color_thres_data.load_transformation_matrix()

# -------------------------------------------------- 
# SECTION 1: Collect Subject Information
# --------------------------------------------------
# Prompt the experimenter for subject details (ID, initials, session number)
subject_id, subject_init, session_today = get_experiment_info_custom()

# Define the primary network disk path for storing experiment files
networkDisk_path = get_path("network_disk_windows")

# Create a subject-specific directory path for storing their session data
path_sub = os.path.join(networkDisk_path, f'sub{subject_id}', 'practice')

# Attempt to load the experiment manager state from a previously saved session file
try:
    # Construct the expected filename for the experiment record
    expt_info = f'sub{subject_id}_{subject_init}_expt_record_practice.pkl'
    path_metadata = os.path.join(path_sub, expt_info)
    
    # Load the experiment state if the file exists
    expt_file_manager = ExperimentFileManager.load_state(path_metadata)
except:
    # If no prior session exists, initialize a new experiment file manager
    expt_file_manager = ExperimentFileManager(subject_id, 
                                              subject_init,
                                              networkDisk_path,
                                              is_practice=True)

# Create a new session file for the current session
_, communicator_file_name = expt_file_manager.create_session_file(session_today)

# List all existing files for the subject
expt_file_manager.list_files()

# -------------------------------------------------------- 
# SECTION 2: Set Up Communication Between Two Computers
# --------------------------------------------------------
# Establish a communication interface via text files stored in the network directory
communicator = CommunicateViaTextFile(expt_file_manager.path_sub, 
                                      retry_delay=3/60, #1 frame
                                      timeout=1200) #1200s = 20 mins

# Check for new messages in the communication file and handle them accordingly
communicator.check_and_handle_file(communicator_file_name)

# Step 1: Initialize communication protocol
print("Initializing communication...")
communicator.initialize_communication()
print("Initialization complete.")

# Step 2: Update experiment status to confirm successful initialization
expt_file_manager.status_updates('Confirmed')

# ---------------------------------------------------------------
# SECTION 3: Retrieve Pre-Generated MOCS Trials
# ---------------------------------------------------------------
# The experiment interleaves two types of trials: MOCS and AEPsych.
# - MOCS (Method of Constant Stimuli) trials are pre-generated in a separate script 
#   (see Simulate_MOCS_trials_W.py) and shuffled within that script.
#
# Structure of the Pre-Generated MOCS Trials:
# - 25 unique reference colors and 25 chromatic directions (generated via Sobol sequences)
# - Each condition has 12 levels on the psychometric curve
# - Each level is repeated 20 times
# - Total number of MOCS trials = 25 x 12 x 20 = 6000 trials
#
# Block Organization:
# - The 6000 trials are divided into 20 blocks (corresponding to 20 repetitions)
# - Within each block, 300 trials are shuffled so that every subset of 20 trials 
#   covers all conditions once.
path_pregenerated_trials = os.path.join(baseDir, 'ELPS_analysis', 
                                        'Simulation_DataFiles', 'MOCS',
                                        'Isoluminant plane','gt_Wishart')

# Subject-Specific MOCS Trials:
# - Each subject gets a unique set of MOCS trials, determined by a different random seed.
# - In the main experiment, the seed is based on the subject ID.
# - In the practice script (run_4d_expt_practice.py), the seed is modified to be 
#   `subject_id * 10000` to ensure subjects do not practice on the same exact trials 
#   they will encounter in the main experiment. This prevents over-training on MOCS trials.
subject_seed_MOCS = subject_id * 10000
file_name_pregenerated_trials = "Sim2dTask_colorDiscrimination_Isoluminant plane_"+\
    f"MOCSTrials_25refs_12levels_25trialsPerLevel_sub4_Sobol_seed{subject_seed_MOCS}.pkl"
fullpath_pregenerated_MOCS_trials = os.path.join(path_pregenerated_trials, 
                                                 file_name_pregenerated_trials)

# Define the number of trials per session.
# Once set in the first session, this value remains unchanged for subsequent sessions.
NTRIALS_MOCS_PERSESSION = 20

# Retrieve a subset of MOCS trials based on the current session number.
# Example:
# - If session_today = 1, get trials [0:NTRIALS_MOCS_PERSESSION].
# - If session_today = n, get trials [(n-1)*NTRIALS_MOCS_PERSESSION : n*NTRIALS_MOCS_PERSESSION].
MOCS_subset_trials, idxTrial_MOCS = LoadExptInfo.load_pregenerated_MOCS(\
                                        fullpath_pregenerated_MOCS_trials,
                                        session_today, 
                                        NTRIALS_MOCS_PERSESSION)

# --------------------------------------------------------------------
# SECTION 4a: Set Up AEPsych Configuration and Interleave Trial Types
# --------------------------------------------------------------------
# This section configures the AEPsych adaptive sampling procedure and determines
# how AEPsych and MOCS trials are interleaved during the experiment.

# Define the directory path where the configuration files are stored.
path_str_config = os.path.join(baseDir, 'META_analysis', 'customized_configs')

# Define the specific configuration file for this experiment setup.
file_config = f"single_{COLOR_DIMENSION}d_colorDiscrimination_EAVC_4strats_new.ini"

# Initialize the configuration generator with the specified parameters.
config_gen = ConfigGenerator(COLOR_DIMENSION,
                             base_path=path_str_config,
                             load_file_name=file_config, 
                             load_default_config=False,
                             version_new = True)

# Retrieve the strategy names from the 'common' section of the configuration file.
strat_names = config_gen._string_to_list('common', 'strategy_names')

# Define the number of trials for each strategy.
# This configuration remains the same across all sessions once set in the first session.
# These are more than enough sobol trials for the practice. We will unlikely to use them all.
NTRIALS_STRAT = [500, 500, 500, 1] 

# Update the configuration file with the specified number of trials per strategy.
for strat_n, nT in zip(strat_names, NTRIALS_STRAT):
    config_gen.modify_configurations(strat_n, 'min_asks', str(nT))
    
# Compute the total number of trials across all strategies.
NTRIALS = np.sum(np.array(NTRIALS_STRAT))

# Convert the updated configuration object to a string format for further processing.
config = config_gen.get_config_as_string()
config_all = [config]

# --------------------------------------------------------------------
# SECTION 4b: Define Interleaving of AEPsych and MOCS Trials
# --------------------------------------------------------------------
# Specify the number of AEPsych trials per session.
# Like MOCS trials, this value remains unchanged across all sessions once set in the first session.
NTRIALS_AEPSYCH_PERSESSION = 20
NTRIALS_PERSESSION = NTRIALS_MOCS_PERSESSION + NTRIALS_AEPSYCH_PERSESSION

# Interleaving Strategy:
# - AEPsych and MOCS trials are paired and shuffled to ensure an even distribution.
# - Within each pair, the order of MOCS and AEPsych trials is randomized.
# - This prevents runs of more than two consecutive trials of the same type.
# - The number of blocks (nBlocks) is determined by the total number of AEPsych and 
#       MOCS trials divided by 2.
# - If the total number of AEPsych and MOCS trials differ, nBlocks must be adjusted 
#       to be divisible by both.

sim_interleaved_trial_sequence = ExperimentTrialSequence(
    nTrials_AEPsych  = NTRIALS_AEPSYCH_PERSESSION, 
    pregenerated_MOCS = MOCS_subset_trials,
    nBlocks = NTRIALS_PERSESSION // 2,
    break_trials = [10]
)

# Generate the initial interleaved trial sequence using the defined random seed.
subject_seed_interleaveTrials = subject_seed_MOCS + session_today
sim_interleaved_trial_sequence.generate_init_sequence(seed=subject_seed_interleaveTrials)

# --------------------------------------------------
# SECTION 5: Use AEPsych for Trial Placement
# --------------------------------------------------
# Define the database file for storing experiment data specific to the subject.
db_file_name = f"ColorDiscrimination_{COLOR_DIMENSION}dTask_{plane_2D}_sub{subject_id}_practice.db"
server = AEPsychServer(database_path=os.path.join(path_sub, db_file_name))
client = AEPsychClient(server=server)  

# Trial Setup Strategy Based on Session:
# --------------------------------------
# - First Session:
#   1. Configure the experiment using the configuration file.
#   2. Generate and shuffle a list of Sobol scalers to balance task difficulty.
#      - Example: If SOBOL_SCALER = [1/4, 2/4, 3/4, 1] and NTRIALS_STRAT = [500, 500, 500, 5000],
#        then 1/4 is repeated 500 times, 2/4 is repeated 500 times, and so on.
#      - Shuffling ensures a more balanced difficulty distribution.
#
# - Subsequent Sessions:
#   1. Replay all past trials and resume the experiment from the database.
#   2. Retrieve the stored Sobol scaler list from the first session and select
#      the appropriate subset based on the current session number.

if session_today == 1: 
    # Step 1: Send the experiment configuration to the AEPsych client.
    client.configure(config_str=config)
    
    # Define the Sobol scaler values corresponding to different strategy levels.
    SOBOL_SCALER = [1/4, 2/4, 3/4, 1] 
    
    # Define the maximum strategy level to shuffle (to balance difficulty).
    shuffle_sobol_scaler_max_strat = 3  # Shuffles up to the third strategy level.
    
    # Shuffle Sobol scalers for balanced task difficulty.
    subject_seed_sobol_scaler = subject_seed_MOCS
    customized_sobol_scaler_all = shuffle_sobol_trials(
        SOBOL_SCALER, NTRIALS_STRAT, shuffle_sobol_scaler_max_strat, seed=subject_seed_sobol_scaler)
    
    # Extract the Sobol scalers for the current session.
    idxTrial_AEPsych = [0, NTRIALS_AEPSYCH_PERSESSION]
    customized_sobol_scaler = customized_sobol_scaler_all[:NTRIALS_AEPSYCH_PERSESSION]
else:
    # Retrieve experiment IDs from the database (used to replay past trials).
    exp_ids = [rec.unique_id for rec in server.db.get_master_records()]
    print(exp_ids)

    # Replay all past sessions up to the latest experiment.
    server.replay(exp_ids[-1], skip_computations=True)
    
    # Resume the last session (following guidance from Jason Chow).
    server.handle_request({"type": "resume", "message": {"strat_id": "0"}})
    server._db_master_record = server.db.get_master_record(exp_ids[-1])
    
    # Load the Sobol scalers that were generated in the first session.
    file_path_session1 = os.path.join(path_sub,  f"ColorDiscrimination_{COLOR_DIMENSION}dExpt_{plane_2D}_sub{subject_id}_session1_practice.pkl")
    customized_sobol_scaler, idxTrial_AEPsych, _ = LoadExptInfo.load_pregenerated_val_scaler(
        file_path_session1, session_today, NTRIALS_AEPSYCH_PERSESSION)

#%% 
# --------------------------------------------------
# SECTION 6: Run the Experiment!
# --------------------------------------------------
# This section executes the experiment by generating and running interleaved MOCS and AEPsych trials.

try:
    # Create an instance of the experiment trial generation class.
    expt_trials = ExptTrialGeneration(
        COLOR_DIMENSION,
        config_all, 
        communicator=communicator,  # Handles communication with the second computer
        color_thres=color_thres_data,  # Stores transformation matrices
        customized_val_scaler=customized_sobol_scaler  # Shuffled Sobol scalers
    )
    
    # Trial Timing and Interleaving Strategy
    # - AEPsych can occasionally take a long time to determine the next trial.
    # - To avoid excessive wait times for participants, we insert a MOCS trial if needed.
    #
    # Trial Timing Breakdown:
    # - After a response: blank screen (0.2s) + feedback (0.5s) + ITI (1.5s) 
    #                       + fixation (0.5s) + blank screen (0.2s) → Total = 2.9s
    # - If AEPsych fails to determine the next trial within 2.9s, a MOCS trial is inserted.
    # - If AEPsych still does not respond, it has an additional 4.1s 
    #                      (including stimulus presentation, 1s, and response time, ~0.2s) to catch up.
    #
    # The max wait time before inserting a MOCS trial is defined as:
    max_wait_time_before_bumpingMOCS = [2.9, 4.1]
    
    # Run the experiment with interleaved MOCS trials inserted when necessary.
    sim_interleaved_trial_sequence = expt_trials.run_experiment_wMOCSinserted(
        client,
        sim_interleaved_trial_sequence,
        max_wait_time=max_wait_time_before_bumpingMOCS
    )
    
    # Finalization and Data Export
    # Close communication and update the experiment status.
    print("Finalizing communication...")
    communicator.finalize()
    print("Communication finalized.")
    
    # Update the experiment status to 'Done'.
    expt_file_manager.status_updates('Done')
except Exception as e: 
    print(f"An error occurred: {e}")
    
# Collect and save any comments from the experiment session.
expt_file_manager.add_comments(get_comment_after_session())

# Export the experiment log to a text file for record-keeping.
# Define the output file name for export.
output_txt = f'trial_status_sub{subject_id}_session{session_today}.txt'
expt_file_manager.export_expt_log_txt(output_txt, sim_interleaved_trial_sequence)

# --------------------------------------------------
# SECTION 7: Save data
# --------------------------------------------------
output_file =  f"ColorDiscrimination_{COLOR_DIMENSION}dExpt_{plane_2D}_"+\
    f"sub{subject_id}_session{session_today}_practice.pkl"
full_path2 = os.path.join(path_sub, output_file)

variable_names = ['python_version','aepsych_version', 'COLOR_DIMENSION','plane_2D',
                  'color_thres_data', 'subject_id', 'subject_init', 'session_today', 
                  'expt_file_manager', 'communicator', 'fullpath_pregenerated_MOCS_trials',
                  'NTRIALS_MOCS_PERSESSION', 'idxTrial_MOCS', 'MOCS_subset_trials',
                  'file_config', 'config_all','strat_names', 'NTRIALS_STRAT', 'NTRIALS',
                  'NTRIALS_AEPSYCH_PERSESSION', 'sim_interleaved_trial_sequence',
                  'db_file_name','SOBOL_SCALER', 'shuffle_sobol_scaler_max_strat',
                  'customized_sobol_scaler_all','idxTrial_AEPsych','customized_sobol_scaler',
                  'expt_trials','max_wait_time_before_bumpingMOCS', 'subject_seed_MOCS',
                  'subject_seed_interleaveTrials', 'subject_seed_sobol_scaler']
vars_dict = {}

for var_name in variable_names:
    try:
        # Check if the variable exists in the global scope
        vars_dict[var_name] = eval(var_name)
    except NameError:
        # If the variable does not exist, assign None and print a message
        vars_dict[var_name] = None
        print(f"Variable '{var_name}' does not exist. Assigned as None.")

# Write the list of dictionaries to a file using pickle
with open(full_path2, 'wb') as f:
    pickled.dump(vars_dict, f)
